
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
  namespace: fleetman
spec:
  selector:
    app: fleetman-position-simulator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
