
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongodb
  namespace: fleetman
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-mongodb
  template:
    metadata:
      labels:
        app: fleetman-mongodb
    spec:
      containers:
      - name: fleetman-mongodb
        image: mongo:3.6.23
        ports:
        - containerPort: 27017
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production-microservice"
