
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
  namespace: fleetman
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
      - name: fleetman-queue
        image: supinfo4kube/queue:1.0.1
        ports:
        - containerPort: 61616
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production-microservice"
