apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
  namespace: fleetman
spec:
  selector:
    app: fleetman-position-tracker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
