apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  namespace: fleetman
spec:
  selector:
    app: fleetman-queue
  ports:
    - protocol: TCP
      port: 61616
      targetPort: 61616
  type: ClusterIP
